USE ChatApplication

DROP TABLE IF EXISTS Chat.Follower;
DROP TABLE IF EXISTS Chat.[Like];
DROP TABLE IF EXISTS Chat.CommunityUser;
DROP TABLE IF EXISTS Chat.CommunityTag;
DROP TABLE IF EXISTS Chat.PostTag;
DROP TABLE IF EXISTS Chat.Tag;
DROP TABLE IF EXISTS Chat.PostImage;
DROP TABLE IF EXISTS Chat.Post;
DROP TABLE IF EXISTS Chat.Community;
DROP TABLE IF EXISTS Chat.Visibility;
DROP TABLE IF EXISTS Chat.[User];
DROP TABLE IF EXISTS Chat.[Image];

CREATE TABLE Chat.[Image]
(
	imageId INT IDENTITY(1, 1) PRIMARY KEY,
	imageUrl NVARCHAR(500) NOT NULL UNIQUE,
	publicId NVARCHAR(100) NOT NULL UNIQUE,
)

CREATE TABLE Chat.[User]
(
	userId INT IDENTITY(1, 1) PRIMARY KEY,
	name NVARCHAR(30) NOT NULL,
	handle NVARCHAR(30) NOT NULL UNIQUE,
	imageId INT FOREIGN KEY
		REFERENCES Chat.[Image](imageId) NOT NULL,
	bio NVARCHAR(150),
	email NVARCHAR(128),
	ethereumAddress NVARCHAR(64),
	status BIT NOT NULL DEFAULT 1,
	createdDate DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
)

CREATE UNIQUE INDEX UQ_User_Email
ON Chat.[User] (email)
WHERE email IS NOT NULL

CREATE UNIQUE INDEX UQ_User_Ether
ON Chat.[User] (ethereumAddress)
WHERE ethereumAddress IS NOT NULL

CREATE TABLE Chat.Follower
(
	followedUserId INT FOREIGN KEY
		REFERENCES Chat.[User](userId) NOT NULL,
	followerUserId INT FOREIGN KEY
		REFERENCES Chat.[User](userId) NOT NULL,
	followDate DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CONSTRAINT PK_Follower PRIMARY KEY (followedUserId, followerUserId),
	CONSTRAINT CHK_FollowedIsNotFollower CHECK (followedUserId <> followerUserId)
)

CREATE TABLE Chat.Visibility
(
	name NVARCHAR(10) PRIMARY KEY
)

CREATE TABLE Chat.Community
(
	communityId INT IDENTITY(1, 1) PRIMARY KEY,
	creatorId INT FOREIGN KEY
		REFERENCES Chat.[User](userId) NOT NULL,
	name NVARCHAR(50) NOT NULL,
	description NVARCHAR(200) NOT NULL,
	visbility NVARCHAR(10) FOREIGN KEY
		REFERENCES Chat.Visibility(name),
)

CREATE TABLE Chat.CommunityUser
(
	communityId INT FOREIGN KEY
		REFERENCES Chat.Community(communityId),
	userId INT FOREIGN KEY
		REFERENCES Chat.[User](userId),
	joinDate DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
	CONSTRAINT PK_CommUser PRIMARY KEY (communityId, userId)
)

CREATE TABLE Chat.Post
(
	postId INT IDENTITY(1, 1) PRIMARY KEY,
	userId INT FOREIGN KEY
		REFERENCES Chat.[User](userId) NOT NULL,
	content NVARCHAR(280) NOT NULL,
	replyToPostId INT FOREIGN KEY
		REFERENCES Chat.Post(postId),
	communityId INT FOREIGN KEY
		REFERENCES Chat.Community(communityId),
	isPinned BIT NOT NULL DEFAULT 0,
	createdOn DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
)

CREATE TABLE Chat.PostImage
(
	imageId INT FOREIGN KEY
		REFERENCES Chat.[Image](imageId),
	postId INT FOREIGN KEY
		REFERENCES Chat.Post(postId),
	aspectRatio NUMERIC(5, 3) NOT NULL,
	CONSTRAINT PK_ImgPost PRIMARY KEY (imageId, postId)
)

CREATE TABLE Chat.[Like]
(
	userId INT FOREIGN KEY
		REFERENCES Chat.[User](userId),
	postId INT FOREIGN KEY
		REFERENCES Chat.Post(postId),
	likedDate DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CONSTRAINT PK_Like PRIMARY KEY (userId, postId)
)

CREATE TABLE Chat.Tag
(
	tagId INT IDENTITY(1, 1) PRIMARY KEY,
	name NVARCHAR(10) NOT NULL UNIQUE,
	description NVARCHAR(75) NOT NULL,
	color NVARCHAR(20) NOT NULL
)

CREATE TABLE Chat.PostTag
(
	postId INT FOREIGN KEY
		REFERENCES Chat.Post(postId),
	tagId INT FOREIGN KEY
		REFERENCES Chat.Tag(tagId),
	CONSTRAINT PK_PostTag PRIMARY KEY (postId, tagId)
)

CREATE TABLE Chat.CommunityTag
(
	communityId INT FOREIGN KEY
		REFERENCES Chat.Community(communityId),
	tagId INT FOREIGN KEY
		REFERENCES Chat.Tag(tagId),
	CONSTRAINT PK_CommTag PRIMARY KEY (communityId, tagId)
)

--Images
INSERT INTO Chat.[Image](imageUrl, publicId)
VALUES('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682553978/profile-images/f0vtppxhymrmjfldjasn.png', '123'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682131722/profile-images/bht2rbldlgdpatocxpoc.jpg', '124'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554047/profile-images/xlq59bceqkzklwpkngaa.png', '125'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682553979/profile-images/qugejh61xkoukxikckxu.png', '126'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682540821/profile-images/rrllvnuzvzk6ueubtmxk.png', '127'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682556864/profile-images/jjah5mcwuyctykskvd0t.jpg', '128'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554047/profile-images/x4kf2a1uhtmymntfbpqi.png', '129'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682553978/profile-images/vslblkwtcbrkmvhdsuvv.png', '130'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682556864/profile-images/konnbxgwfi0pssk3vw3l.jpg', '131'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682556864/profile-images/burnwmwdtfxdnuipc5bh.jpg', '132'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554047/profile-images/tex9dnivp27pkbe3rf1r.png', '133'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682553979/profile-images/ecl47xudqbrhcrrryfln.png', '134'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554050/profile-images/yvln0ltgyckqud4i7hwk.png', '135'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554091/profile-images/ryxqxnelntlrwqcwajhd.png', '136'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554091/profile-images/fh00noeoqmty4hxmpnl6.jpg', '137'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554091/profile-images/vk7trrw29vo8cewa0tvq.png', '138'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554091/profile-images/qalrwgirrj2u6bfq1nvj.png', '139'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554129/profile-images/xpytake1mc6jhgkrb5jp.png', '140'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682554129/profile-images/aodcuocj72dtcka4tloc.png', '141'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682558757/profile-images/el2gqfjjx5fynu3y4ji1.jpg', '142'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682558757/profile-images/sdy4guoxpmejmamen8sa.jpg', '143'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682558758/profile-images/svra1cf1y8c3mufbdm5j.jpg', '144'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682558761/profile-images/owie13raowqcsxwf6knr.jpg', '145'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682533282/profile-images/scdmb4a700nu3xzzlogr.png', '146'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682369326/profile-images/frsrsyveoe8rd42r7mwk.png', '147'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1681777530/profile-images/q6oxbbkte15zcnchgtgy.png', '148'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1681938349/profile-images/bvpwvmh3zqlaazy1mvrb.png', '149'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1673400263/item_images/qcbl4s4wet0ift8kxyfj.png', '150'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1673400247/item_images/pihzt8aa2r2fo3va0yfx.png', '151'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1673400244/item_images/fgvymicizcsmmwqgbgyh.png', '152'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1673400196/item_images/uxugecee5valahl88zzx.png', '153'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1673400128/item_images/sc3ak4kogmgwtfop5rtv.png', '154'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682867144/profile-images/ilryt4qzvhmipnr0ma5y.jpg', '155'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682867144/profile-images/wpuo0iu2whfo5hmkmzrm.jpg', '156'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682867144/profile-images/kykqfzwczsqqtqtqeo0h.jpg', '157'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682867122/profile-images/umdyiwvv4rbnn6xhabu1.jpg', '158'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682867123/profile-images/k79kz4xuppp9lr2qffj6.jpg', '159'),
('https://res.cloudinary.com/dwg1i9w2u/image/upload/v1682867144/profile-images/zes8z007pwb76atzwocs.jpg', '160');

--Users
INSERT INTO Chat.[User](name, handle, email, imageId, bio) 
VALUES ('Shehd', 'itshehd', 'bigshehd@gmail.com', 1, 'Hi im shead my brother is @algonky'),
('Algonquin', 'algonky', 'agonkington0@gmail.com', 2, 'Yo its alg. Tune out the haters and turn on the tunes'),
('Joshua Starrs', 'jstarrs', 'dripkingjoshy@gmail.com', 3, 'Known for my star shirt'),
('Mr. Banana', 'mistabanana', 'mbanan@gmail.com', 4, 'Known for my star shirt'),
('Happi', 'happithemonkey', 'thehappi@gmail.com', 5, 'Im happi! Always spreading good vibes! ~'),
('Samuel Bankman-Fried', 'thnx4thebread', 'ftxbankaccount@gmail.com', 6, 'CEO of @FTX - Forbes’ “Most Trusted Man In Crypto” - Not your keys, not your crypto!'),
('Marcel', 'bananasuit304', 'nannersuit@gmail.com', 7, 'yea im the one in my profile picture'),
('Soapy Scott', 'papasoap', 'papasoap@gmail.com', 8, 'I like big bubbles and I cannot lie (the other monkeys can’t deny)!'),
('Peterson', 'bluepow', 'mawm@gmail.com', 9, 'I just want a blue powerade'),
('Thatch', 'thethatch3202524', 'thethatch3202524@gmail.com', 10, 'litle cuzin of @itshehd i like climbing on rooves'),
('Machokat', 'bigmacho', 'machokats@gmail.com', 11, 'Coming soon to Arbitrum for FREE… we are still here… 02/22/23'), 
('garkill1', 'rhyams1', 'gdyne1@shinystat.com', 12, 'Pace University'),
('cswenson3', 'nesp3', 'gbeaument3@berkeley.edu', 13, 'Creighton University'),
('gellams5', 'czarfati5', 'bburress5@photobucket.com', 14, 'Arizona Christian University'),
('gellams5', 't', 'hunterstatek@gmail.com', 15, 'Arizona Christian University'),
('admin', 'admin', 'pfannenstielpayton@gmail.com', 16, ':O'),
('Daltfresh', 'deddow0', 'rbasketter0@vistaprint.com', 34, 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis'),
('Tresom', 'hflint1', 'eadlard1@blog.com', 25, 'amet lobortis sapien sapien non mi integer ac neque duis'),
('Domainer', 'ldemarco2', 'bsmorthit2@joomla.org', 26, 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue'),
('Kanlam', 'rdockreay3', 'canthona3@telegraph.co.uk', 26, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl'),
('Namfix', 'ehumblestone4', 'ngurdon4@smugmug.com', 28, 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus'),
('Bitchip', 'jbartle5', 'hgecks5@geocities.com', 26, 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat'),
('Sonsing', 'schurchman6', 'vinett6@dagondesign.com', 33, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus'),
('Ronstring', 'stzarkov7', 'yvinden7@nih.gov', 32, 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae'),
('Voltsillam', 'rgrimmert8', 'croff8@imdb.com', 31, 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci'),
('Voyatouch', 'gcrocket9', 'bmacard9@naver.com', 22, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue'),
('Cookley', 'ishobrooka', 'mhollingtona@storify.com', 29, 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl'),
('Opela', 'jsalzenb', 'smctavyb@xrea.com', 16, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non'),
('Greenlam', 'rgilburtc', 'amcelreec@mtv.com', 30, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere'),
('Stim', 'lstertd', 'sdagleasd@list-manage.com', 33, 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo'),
('Bitchip', 'scopinge', 'jmcgarele@hexun.com', 17, 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut'),
('Mat Lam Tam', 'sbentzf', 'roganf@printfriendly.com', 37, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel'),
('Span', 'rsandefordg', 'gtabramg@shinystat.com', 36, 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula'),
('Zaam-Dox', 'flemasneyh', 'amainsonh@barnesandnoble.com', 13, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis'),
('Duobam', 'roreti', 'ccockei@usnews.com', 12, 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam'),
('Kanlam', 'bwiganj', 'asimmensj@lulu.com', 12, 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit'),
('Lotlux', 'rmcbaynek', 'sfarrak@t.co', 25, 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus'),
('Duobam', 'sdunphyl', 'hcapitanol@house.gov', 18, 'non velit donec diam neque vestibulum eget vulputate ut ultrices'),
('Konklux', 'shamlinm', 'cramsbothamm@wordpress.com', 27, 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et'),
('Overhold', 'farentn', 'skintzeln@eepurl.com', 36, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas'),
('Bytecard', 'sevemyo', 'arazouxo@addthis.com', 25, 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean'),
('It', 'tskylettp', 'amessump@uol.com.br', 21, 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue'),
('Holdlamis', 'ctiddyq', 'lcoasterq@com.com', 28, 'aenean auctor gravida sem praesent id massa id nisl venenatis'),
('Cardguard', 'bbarizeretr', 'msporler@adobe.com', 22, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum'),
('Cardguard', 'mhoricks', 'ewoodhalls@weather.com', 12, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat'),
('Trippledex', 'ccockingst', 'kwimpresst@ocn.ne.jp', 37, 'id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius'),
('Overhold', 'jgreenhaughu', 'pkyffinu@jalbum.net', 37, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel'),
('Quo Lux', 'mdurnov', 'cboornv@gmpg.org', 17, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est'),
('Flexidy', 'fgrzelewskiw', 'lkezarw@bloglovin.com', 32, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl'),
('Quo Lux', 'wscraneyx', 'ffletcherx@infoseek.co.jp', 25, 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra'),
('Sonsing', 'bcisary', 'swaszczykowskiy@123-reg.co.uk', 16, 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti'),
('Rank', 'fhornungz', 'vlaweyz@yellowbook.com', 21, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in'),
('Konklab', 'ddietzler10', 'imccaskill10@walmart.com', 17, 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla'),
('Biodex', 'dweine11', 'dfernant11@amazonaws.com', 38, 'eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo'),
('Mat Lam Tam', 'cmcgeoch12', 'jthurstance12@homestead.com', 27, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna'),
('Domainer', 'kgrealish13', 'mfairs13@weebly.com', 28, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras'),
('Stronghold', 'dnaerup14', 'clonergan14@sbwire.com', 34, 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin'),
('Bitwolf', 'fpinhorn15', 'tluckhurst15@github.io', 14, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non'),
('Mat Lam Tam', 'lgreschik16', 'dkernley16@japanpost.jp', 31, 'praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor'),
('Biodex', 'awashbrook17', 'lsymers17@bravesites.com', 32, 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue'),
('Cardguard', 'alabusquiere18', 'msushams18@bravesites.com', 24, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam'),
('Y-find', 'cberens19', 'thatry19@umn.edu', 24, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor'),
('It', 'jbenardet1a', 'ccaberas1a@eventbrite.com', 30, 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur'),
('Wrapsafe', 'tdunnett1b', 'ecollier1b@wikispaces.com', 24, 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique'),
('Veribet', 'jfeavearyear1c', 'lcharlewood1c@apache.org', 33, 'porttitor pede justo eu massa donec dapibus duis at velit eu est'),
('Ronstring', 'kyewdall1d', 'ctimpany1d@usda.gov', 36, 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit'),
('Alphazap', 'mkuhlmey1e', 'lschusterl1e@theglobeandmail.com', 23, 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia'),
('Y-Solowarm', 'gtotaro1f', 'khafford1f@harvard.edu', 31, 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede'),
('Sub-Ex', 'mwinter1g', 'pgarfitt1g@go.com', 31, 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat'),
('Cardguard', 'bciccarelli1h', 'btownsley1h@rambler.ru', 24, 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis'),
('Zamit', 'jaspland1i', 'ybotright1i@dailymail.co.uk', 37, 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris'),
('Tresom', 'cutley1j', 'ceastbury1j@disqus.com', 15, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar'),
('Sonsing', 'aibert1k', 'cwild1k@ihg.com', 24, 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis'),
('Opela', 'efinden1l', 'dobington1l@kickstarter.com', 29, 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula'),
('Lotstring', 'ffranzen1m', 'kallott1m@live.com', 35, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue'),
('Y-find', 'rwisdom1n', 'hblowick1n@nsw.gov.au', 37, 'ac est lacinia nisi venenatis tristique fusce congue diam id'),
('Veribet', 'abaudesson1o', 'ldinnies1o@marriott.com', 29, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede'),
('Gembucket', 'bmunnion1p', 'lriglar1p@blinklist.com', 17, 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus'),
('Alphazap', 'ecliss1q', 'sfayter1q@netscape.com', 38, 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla'),
('Zaam-Dox', 'rbossons1r', 'jstellin1r@canalblog.com', 16, 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis'),
('Hatity', 'bbaudichon1s', 'lschaben1s@springer.com', 24, 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae'),
('Tampflex', 'jhowsam1t', 'kgainsburgh1t@sogou.com', 29, 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget'),
('Hatity', 'smatijevic1u', 'idarrigone1u@zimbio.com', 23, 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet'),
('It', 'sdrought1v', 'sascough1v@indiatimes.com', 25, 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique'),
('Mat Lam Tam', 'gcordelet1w', 'dsirett1w@xinhuanet.com', 20, 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque'),
('Tin', 'eklimov1x', 'rmcnabb1x@addtoany.com', 13, 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin'),
('Sub-Ex', 'kglasby1y', 'tcardiff1y@tripod.com', 18, 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla'),
('Y-find', 'leam1z', 'jrotham1z@weibo.com', 32, 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo'),
('Zamit', 'htuke20', 'mswayland20@tumblr.com', 32, 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam'),
('Zaam-Dox', 'kwalne21', 'lthacke21@rambler.ru', 22, 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat'),
('Daltfresh', 'bizkovitch22', 'nlongmate22@china.com.cn', 24, 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien'),
('Cookley', 'tettles23', 'mivanishin23@microsoft.com', 20, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta'),
('Temp', 'sbreazeall24', 'ubiss24@woothemes.com', 35, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget'),
('Daltfresh', 'deymor25', 'mleggitt25@jugem.jp', 14, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien'),
('Bytecard', 'kstickler26', 'dvanthoff26@ucoz.ru', 30, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate'),
('Ronstring', 'nshewan27', 'lwisam27@uol.com.br', 27, 'mi in porttitor pede justo eu massa donec dapibus duis'),
('Bamity', 'ihuleatt28', 'rgoaks28@weibo.com', 12, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi'),
('Voltsillam', 'cchatain29', 'bmilmoe29@shop-pro.jp', 14, 'lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea'),
('Tin', 'kledstone2a', 'zrosenstock2a@auda.org.au', 22, 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus'),
('Tres-Zap', 'mpike2b', 'dmotten2b@sfgate.com', 19, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus');


--Posts
INSERT INTO Chat.Post (userId, content)
VALUES (2, 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa'),
(4, 'ante ipsum primis in'),
(9, 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin'),
(5, 'vestibulum aliquet ultrices erat'),
(11, 'in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in'),
(4, 'adipiscing lorem vitae mattis nibh'),
(11, 'vitae quam'),
(2, 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam'),
(6, 'sociis natoque'),
(10, 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra'),
(5, 'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae'),
(10, 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus'),
(1, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis'),
(11, 'nunc vestibulum ante ipsum primis in faucibus'),
(10, 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi'),
(6, 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus'),
(10, 'quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in'),
(11, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum'),
(9, 'mauris'),
(1, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet'),
(6, 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc'),
(6, 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna'),
(3, 'sapien placerat ante nulla justo aliquam quis turpis eget elit'),
(6, 'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla'),
(11, 'hac habitasse'),
(6, 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque'),
(8, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante'),
(9, 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet'),
(7, 'purus aliquet at feugiat non pretium quis'),
(11, 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla'),
(1, 'blandit non interdum in'),
(4, 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus'),
(10, 'sit amet justo morbi'),
(10, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac'),
(6, 'sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus'),
(4, 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem'),
(8, 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra'),
(6, 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula'),
(4, 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a'),
(5, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id'),
(11, 'vel'),
(11, 'lectus vestibulum quam sapien varius ut blandit'),
(5, 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et'),
(11, 'posuere'),
(8, 'ipsum'),
(7, 'odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi'),
(1, 'sodales sed tincidunt eu felis fusce posuere felis'),
(3, 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et'),
(2, 'quam'),
(5, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque'),
(6, 'eu massa donec dapibus duis at velit eu est congue elementum in hac'),
(7, 'mauris eget massa'),
(9, 'at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum'),
(7, 'non mauris morbi non lectus aliquam sit amet diam in'),
(10, 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis'),
(1, 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien'),
(2, 'mauris viverra'),
(6, 'in tempus sit amet sem fusce consequat nulla'),
(8, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque'),
(11, 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget'),
(3, 'in lectus pellentesque at nulla suspendisse potenti cras'),
(11, 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor'),
(2, 'semper est quam pharetra magna ac consequat metus sapien ut'),
(8, 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante'),
(11, 'ultrices posuere cubilia curae duis faucibus accumsan odio'),
(1, 'vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id'),
(7, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis'),
(7, 'eleifend donec ut dolor morbi vel lectus in quam'),
(2, 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet'),
(4, 'nisi nam'),
(3, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed'),
(10, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna'),
(4, 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet'),
(10, 'odio donec vitae nisi'),
(2, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus'),
(10, 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh'),
(7, 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat'),
(7, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris'),
(11, 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis'),
(7, 'integer aliquet'),
(5, 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim'),
(3, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante'),
(9, 'semper'),
(9, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam'),
(9, 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc'),
(10, 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet'),
(1, 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id'),
(4, 'dapibus augue vel accumsan tellus nisi'),
(5, 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede'),
(1, 'id nulla ultrices'),
(4, 'id justo'),
(10, 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis'),
(3, 'luctus et ultrices posuere cubilia curae nulla dapibus'),
(3, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien'),
(10, 'nec'),
(11, 'pellentesque'),
(7, 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio'),
(2, 'volutpat convallis morbi'),
(10, 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis'),
(3, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices');

--Comments
INSERT Chat.Post (userId, content, replyToPostId)
VALUES (9, 'et eros vestibulum ac est', 72),
(64, 'phasellus in felis donec semper', 46),
(50, 'quis odio consequat', 85),
(9, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis', 58),
(16, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 69),
(69, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 49),
(64, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 73),
(82, 'ornare imperdiet sapien urna pretium', 21),
(40, 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor', 80),
(56, 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', 56),
(52, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi', 42),
(96, 'nullam orci pede venenatis non sodales', 33),
(32, 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', 21),
(52, 'non', 85),
(13, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 11),
(91, 'mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 5),
(9, 'ac nulla sed', 37),
(86, 'lectus pellentesque', 13),
(63, 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', 96),
(18, 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 83),
(88, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', 93),
(63, 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 19),
(63, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 51),
(62, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 84),
(31, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 22),
(94, 'odio curabitur convallis duis consequat dui nec nisi volutpat', 73),
(63, 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 12),
(17, 'dui maecenas tristique est et tempus semper est quam pharetra magna', 95),
(94, 'nibh ligula nec sem duis aliquam convallis nunc proin at', 67),
(25, 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', 26),
(12, 'ut nunc vestibulum ante ipsum primis', 6),
(93, 'nulla ultrices aliquet maecenas leo odio condimentum', 47),
(11, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', 97),
(57, 'ac neque duis bibendum', 79),
(49, 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna', 25),
(40, 'ipsum aliquam non mauris', 35),
(30, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis', 36),
(27, 'dapibus', 41),
(93, 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 83),
(88, 'nulla tempus vivamus in', 8),
(43, 'sit amet justo morbi ut', 100),
(29, 'vel ipsum praesent blandit lacinia erat vestibulum sed', 85),
(86, 'aliquet ultrices', 25),
(78, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam', 21),
(46, 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', 29),
(73, 'nulla eget eros elementum pellentesque quisque porta volutpat erat', 94),
(75, 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 98),
(59, 'iaculis diam erat fermentum justo nec condimentum neque sapien', 92),
(91, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 94),
(68, 'nisi at nibh in hac habitasse platea dictumst aliquam', 3),
(92, 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 31),
(14, 'interdum in', 71),
(52, 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 54),
(63, 'sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo', 2),
(100, 'non mattis pulvinar', 64),
(16, 'libero ut massa volutpat', 100),
(54, 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 67),
(61, 'in felis', 42),
(19, 'luctus rutrum nulla', 37),
(60, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', 51),
(23, 'odio', 63),
(90, 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 79),
(78, 'fringilla rhoncus', 90),
(15, 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam', 4),
(64, 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit', 80),
(4, 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 19),
(9, 'nulla facilisi cras non velit nec', 93),
(66, 'eu magna', 95),
(44, 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 69),
(95, 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 1),
(47, 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', 94),
(20, 'duis bibendum morbi non quam nec dui luctus rutrum', 98),
(93, 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 60),
(49, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis', 71),
(56, 'luctus', 27),
(81, 'volutpat dui maecenas tristique est et tempus semper est quam', 16),
(55, 'erat vestibulum sed magna at', 43),
(6, 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet', 56),
(5, 'aliquet maecenas leo odio condimentum id luctus', 48),
(53, 'leo rhoncus sed vestibulum sit amet', 26),
(74, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 13),
(82, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 33),
(58, 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie', 3),
(31, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', 71),
(29, 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat', 100),
(36, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 65),
(4, 'a nibh in quis justo maecenas rhoncus aliquam', 31),
(67, 'morbi non lectus aliquam', 74),
(57, 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et', 59),
(26, 'curabitur in libero', 39),
(68, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 58),
(86, 'felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis', 72),
(78, 'orci mauris lacinia', 84),
(61, 'ut erat id mauris vulputate elementum', 70),
(35, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', 14),
(90, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', 6),
(57, 'lacinia nisi venenatis tristique fusce congue diam id ornare', 38),
(85, 'ante', 83),
(71, 'tempus', 13),
(56, 'sed magna at nunc commodo placerat praesent', 11),
(21, 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit', 63),
(35, 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget', 65),
(76, 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 39),
(11, 'metus aenean fermentum donec', 76),
(35, 'ut dolor morbi vel lectus in quam fringilla', 7),
(5, 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', 10),
(3, 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 30),
(48, 'nunc viverra dapibus nulla suscipit ligula in lacus', 29),
(15, 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius', 46),
(38, 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', 12),
(52, 'vulputate ut ultrices vel', 16),
(48, 'erat quisque erat eros viverra eget congue eget semper rutrum', 95),
(100, 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 97),
(26, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 71),
(85, 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat', 89),
(26, 'nisl', 34),
(91, 'turpis enim', 28),
(99, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin', 40),
(21, 'posuere nonummy integer non velit donec diam neque', 90),
(26, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 74),
(81, 'commodo placerat praesent', 66),
(23, 'gravida sem praesent id', 64),
(2, 'semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in', 75),
(20, 'pede lobortis ligula sit amet', 42),
(81, 'luctus rutrum nulla tellus in sagittis dui', 5),
(64, 'morbi non lectus', 34),
(57, 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet', 61),
(33, 'dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', 46),
(7, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', 100),
(74, 'non pretium', 65),
(44, 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', 13),
(69, 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est', 48),
(75, 'purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam', 50),
(92, 'viverra', 85),
(89, 'magna vulputate luctus', 13),
(76, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur', 80),
(65, 'vehicula consequat morbi a ipsum integer a nibh', 71),
(65, 'morbi vel lectus', 44),
(70, 'a nibh in quis justo', 19),
(64, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 2),
(23, 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 81),
(57, 'curae donec pharetra magna', 83),
(18, 'sagittis dui', 4),
(81, 'sapien ut nunc vestibulum ante ipsum primis in faucibus', 36),
(29, 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 74),
(76, 'lectus in quam fringilla rhoncus mauris enim', 87),
(99, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 88),
(87, 'ipsum primis in faucibus orci luctus et ultrices posuere', 66),
(77, 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', 79),
(73, 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 99),
(51, 'augue vel', 76),
(84, 'blandit non', 67),
(82, 'vel est donec odio justo sollicitudin ut suscipit a', 51),
(62, 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 42),
(65, 'feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 16),
(52, 'ut erat id mauris vulputate elementum nullam', 25),
(85, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 94),
(88, 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', 10),
(20, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id', 8),
(41, 'vitae', 37),
(16, 'duis bibendum morbi non quam', 15),
(46, 'aenean sit amet justo morbi ut', 12),
(75, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis', 28),
(69, 'eget eros elementum pellentesque quisque', 86),
(44, 'est congue', 25),
(79, 'tincidunt eget tempus vel pede', 90),
(17, 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 80),
(73, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices', 37),
(46, 'neque', 73),
(7, 'fermentum donec ut mauris eget massa tempor convallis nulla', 93),
(66, 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', 49),
(91, 'justo pellentesque viverra pede ac diam', 8),
(1, 'molestie sed justo pellentesque viverra pede', 51),
(62, 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras', 30),
(38, 'cras mi pede', 31),
(16, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 73),
(38, 'pharetra', 27),
(89, 'nibh in lectus', 81),
(50, 'dictumst etiam faucibus cursus', 97),
(22, 'et eros vestibulum ac', 3),
(77, 'diam cras pellentesque volutpat dui maecenas tristique est et', 53),
(26, 'erat eros viverra eget congue eget semper rutrum', 61),
(59, 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', 50),
(66, 'donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', 71),
(72, 'placerat ante nulla justo aliquam quis', 45),
(63, 'in sagittis dui vel nisl duis', 80),
(58, 'volutpat dui maecenas tristique est et tempus semper est quam', 30),
(49, 'sociis natoque penatibus et magnis dis', 87),
(100, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet', 41),
(95, 'duis mattis egestas metus aenean fermentum donec ut mauris eget', 78),
(16, 'sed nisl nunc rhoncus dui vel sem sed sagittis', 73),
(92, 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 1),
(17, 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 46),
(10, 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet', 84),
(11, 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum', 12),
(85, 'dapibus', 38),
(12, 'nec dui luctus rutrum nulla', 78),
(43, 'nullam molestie nibh in lectus pellentesque at nulla', 64),
(65, 'ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu', 43),
(74, 'justo in hac habitasse platea dictumst etiam', 55),
(52, 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 23),
(40, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', 58),
(62, 'rutrum nulla', 85),
(72, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 89),
(54, 'feugiat et eros', 49),
(55, 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 30),
(43, 'hendrerit at', 96),
(46, 'interdum venenatis turpis', 12),
(76, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 25),
(18, 'at velit vivamus vel nulla eget', 41),
(59, 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 11),
(19, 'rutrum nulla', 19),
(75, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', 9),
(84, 'etiam justo etiam pretium iaculis justo in hac', 32),
(72, 'tortor id nulla', 47),
(91, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 88),
(33, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 7),
(91, 'diam in magna', 53),
(77, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 30),
(77, 'libero nullam sit amet turpis elementum ligula', 13),
(50, 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo', 61),
(22, 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris', 49),
(96, 'nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 13),
(30, 'accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 79),
(45, 'amet cursus id turpis integer aliquet massa', 39),
(29, 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 49),
(22, 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 77),
(38, 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum', 36),
(55, 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 93),
(22, 'aliquam sit amet diam in magna bibendum imperdiet', 14),
(18, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', 78),
(48, 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante', 10),
(79, 'ut', 30),
(11, 'lobortis convallis tortor', 70),
(88, 'magna vulputate luctus cum sociis natoque penatibus et magnis', 97),
(77, 'dolor morbi vel', 4),
(46, 'erat curabitur gravida nisi at', 26),
(52, 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 25),
(2, 'dapibus at diam', 58),
(75, 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 35),
(50, 'semper', 10),
(82, 'pellentesque viverra pede ac diam cras pellentesque', 27),
(77, 'libero convallis eget eleifend luctus ultricies eu', 16),
(9, 'interdum mauris ullamcorper purus sit amet nulla quisque arcu', 30),
(14, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor', 58),
(97, 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', 84),
(44, 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel', 65),
(27, 'amet lobortis sapien', 96),
(41, 'praesent blandit nam nulla integer pede justo lacinia', 47),
(1, 'enim in tempor turpis', 8),
(62, 'congue vivamus metus', 59),
(2, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est', 81),
(87, 'felis sed interdum venenatis turpis enim blandit mi in', 97),
(74, 'in quam', 80),
(45, 'est et tempus semper est quam pharetra magna ac consequat metus sapien ut', 91),
(4, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 78),
(25, 'lorem id ligula suspendisse', 82),
(9, 'ridiculus mus etiam vel augue vestibulum', 14),
(81, 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien', 80),
(31, 'dictumst maecenas ut massa quis augue', 21),
(8, 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', 3),
(66, 'non mi integer ac', 48),
(48, 'at nibh in hac habitasse platea dictumst', 44),
(36, 'orci vehicula condimentum curabitur in libero ut', 3),
(56, 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', 54),
(16, 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in', 37),
(12, 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', 71),
(53, 'posuere cubilia curae nulla', 65),
(4, 'tempus vivamus in felis eu sapien cursus', 60),
(46, 'ultrices posuere cubilia curae nulla dapibus dolor vel est', 73),
(64, 'placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus', 98),
(1, 'felis donec semper sapien a libero nam dui proin', 27),
(79, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 68),
(28, 'consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam', 26),
(31, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio', 40),
(7, 'sit amet justo morbi ut odio cras mi pede malesuada', 59),
(47, 'ut dolor morbi vel lectus in quam fringilla rhoncus', 53),
(38, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 4),
(90, 'ut mauris eget massa', 98),
(35, 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut', 64),
(49, 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', 30),
(49, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 11),
(89, 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', 7),
(44, 'est lacinia', 38),
(35, 'dui luctus rutrum nulla', 32),
(45, 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', 90),
(71, 'lacus curabitur at ipsum ac', 41),
(67, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu', 69),
(96, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', 64),
(49, 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 80),
(9, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus', 53),
(24, 'a feugiat et eros vestibulum', 16),
(88, 'molestie hendrerit at vulputate vitae', 64),
(43, 'vestibulum ante ipsum primis in faucibus orci luctus', 6),
(78, 'primis in', 36),
(22, 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', 23),
(72, 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', 70),
(80, 'pulvinar lobortis est phasellus sit amet erat nulla tempus', 62),
(34, 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer', 5),
(16, 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', 51);

--Replies to replies
INSERT INTO Chat.Post(userId, content, replyToPostId)
VALUES (89, 'ante ipsum primis in faucibus orci luctus', 275),
(52, 'amet eleifend pede libero quis orci nullam molestie nibh', 229),
(21, 'posuere cubilia curae duis faucibus accumsan odio curabitur', 221),
(96, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', 180),
(4, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel', 278),
(30, 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium', 193),
(83, 'aliquam lacus morbi quis tortor id', 195),
(70, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', 386),
(4, 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis', 375),
(30, 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 196),
(73, 'quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 297),
(9, 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 360),
(57, 'interdum eu tincidunt in', 179),
(66, 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', 215),
(11, 'auctor gravida sem praesent id massa id nisl', 268),
(45, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 174),
(86, 'id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 354),
(88, 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel', 266),
(79, 'in sagittis dui vel', 337),
(85, 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', 315),
(40, 'felis donec semper', 320),
(35, 'et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', 233),
(55, 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', 252),
(30, 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam', 353),
(10, 'curae donec', 332),
(32, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet', 279),
(72, 'id', 103),
(94, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', 304),
(53, 'nec nisi vulputate nonummy maecenas tincidunt lacus', 265),
(75, 'euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 271),
(44, 'nibh in lectus pellentesque at nulla suspendisse', 347),
(19, 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 384),
(27, 'lobortis convallis tortor risus dapibus', 212),
(45, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 206),
(66, 'dui nec', 283),
(78, 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est', 310),
(53, 'duis ac nibh fusce lacus purus aliquet at feugiat non', 177),
(37, 'primis in faucibus', 165),
(24, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque', 256),
(35, 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', 274),
(24, 'libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo', 341),
(79, 'sapien cursus', 226),
(14, 'eu est congue elementum in hac habitasse platea', 290),
(30, 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio', 109),
(64, 'etiam pretium', 373),
(95, 'eu', 345),
(94, 'a feugiat et eros vestibulum ac est', 160),
(23, 'blandit lacinia erat', 397),
(47, 'sit amet diam in', 399),
(57, 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque', 344),
(10, 'tortor sollicitudin mi', 277),
(60, 'quam sapien varius', 137),
(33, 'in blandit ultrices enim lorem ipsum dolor sit amet', 111),
(93, 'donec', 177),
(4, 'mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac', 276),
(68, 'purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', 267),
(83, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', 276),
(38, 'eget', 148),
(33, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', 207),
(59, 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut', 288),
(42, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in', 302),
(76, 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc', 288),
(81, 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 254),
(3, 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', 374),
(53, 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 198),
(39, 'proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', 265),
(99, 'iaculis diam erat fermentum justo nec condimentum neque sapien', 282),
(42, 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 133),
(99, 'posuere cubilia curae', 249),
(43, 'purus eu magna vulputate luctus cum sociis', 365),
(36, 'vitae', 267),
(82, 'arcu adipiscing molestie hendrerit', 263),
(100, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo', 109),
(67, 'sapien dignissim vestibulum vestibulum', 325),
(46, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 309),
(16, 'metus aenean', 190),
(49, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam', 390),
(61, 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl', 203),
(32, 'nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 288),
(49, 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio', 139),
(5, 'in felis donec semper sapien a libero nam dui proin leo odio porttitor', 261),
(49, 'cubilia curae duis faucibus accumsan odio curabitur', 205),
(21, 'ligula in lacus curabitur', 204),
(36, 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla', 186),
(38, 'arcu libero rutrum ac', 109),
(8, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', 228),
(55, 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 246),
(74, 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', 253),
(10, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', 367),
(30, 'curabitur in libero ut massa volutpat convallis morbi', 121),
(65, 'mauris enim leo rhoncus', 205),
(77, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas', 212),
(49, 'in congue etiam justo etiam pretium iaculis', 167),
(51, 'posuere cubilia curae mauris viverra diam vitae quam', 207),
(84, 'justo eu massa donec', 126),
(54, 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 188),
(75, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula', 122),
(16, 'nec condimentum neque sapien placerat ante nulla justo aliquam', 328),
(94, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 102),
(36, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 281),
(39, 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus', 397),
(83, 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', 156),
(43, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 301),
(55, 'donec dapibus duis at velit eu est', 187),
(73, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 235),
(8, 'duis at velit eu est congue elementum', 395),
(63, 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 313),
(14, 'non mauris morbi', 132),
(41, 'nisl venenatis lacinia aenean sit amet justo morbi ut odio', 209),
(90, 'suspendisse potenti nullam porttitor', 191),
(43, 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', 158),
(45, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', 349),
(80, 'suscipit a feugiat et eros', 258),
(41, 'dapibus duis at velit eu est congue elementum in hac habitasse', 245),
(67, 'et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', 189),
(22, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', 281),
(29, 'etiam pretium iaculis justo in', 308),
(27, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', 177),
(5, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 167),
(6, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 281),
(82, 'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum', 249),
(52, 'augue vel', 188),
(47, 'ac nibh fusce lacus purus aliquet at feugiat non', 325),
(95, 'luctus et ultrices posuere cubilia curae donec pharetra', 298),
(76, 'vulputate ut ultrices vel augue', 292),
(41, 'mattis odio donec vitae nisi nam ultrices libero non', 179),
(17, 'et', 311),
(59, 'purus', 181),
(82, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 323),
(34, 'volutpat erat quisque erat eros viverra eget congue', 195),
(54, 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', 385),
(81, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien', 307),
(50, 'in porttitor pede justo eu massa donec dapibus duis at velit', 237),
(75, 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a', 183),
(69, 'quis lectus suspendisse', 159),
(58, 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', 268),
(24, 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis', 325),
(27, 'suscipit a feugiat et eros', 221),
(30, 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', 380),
(9, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', 117),
(51, 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 269),
(19, 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 278),
(81, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus', 311),
(56, 'volutpat eleifend donec ut dolor morbi vel', 184),
(31, 'potenti nullam porttitor', 296),
(32, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis', 250),
(72, 'ac enim', 137),
(35, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 224),
(33, 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', 148),
(81, 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 160),
(54, 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 265),
(44, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', 226),
(69, 'elementum ligula vehicula consequat', 183),
(10, 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus', 128),
(9, 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', 202),
(17, 'feugiat non pretium', 283),
(69, 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 119),
(38, 'maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum', 274),
(29, 'dictumst maecenas ut massa quis', 400),
(53, 'rhoncus', 146),
(76, 'varius', 117),
(52, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', 264),
(51, 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', 291),
(86, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo', 233),
(32, 'sagittis', 215),
(18, 'ut erat curabitur gravida nisi at nibh in hac habitasse', 214),
(73, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 186),
(73, 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', 384),
(22, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', 137),
(100, 'suspendisse potenti in eleifend quam a odio', 204),
(62, 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 394),
(57, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 236),
(85, 'ipsum primis in faucibus orci luctus et ultrices', 295),
(51, 'augue vestibulum rutrum rutrum neque', 240),
(93, 'tellus semper interdum', 337),
(59, 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et', 359),
(48, 'nascetur ridiculus mus', 368),
(58, 'elit proin risus praesent lectus', 332),
(2, 'at nulla suspendisse potenti cras in purus eu magna', 268),
(41, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 351),
(22, 'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit', 223),
(3, 'turpis donec posuere metus vitae ipsum', 225),
(83, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non', 323),
(80, 'odio curabitur convallis duis consequat dui nec nisi', 104),
(9, 'tincidunt lacus at velit vivamus vel nulla', 390),
(58, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat', 338),
(7, 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor', 291),
(21, 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 192),
(46, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin', 242),
(29, 'blandit non interdum', 278),
(84, 'parturient montes nascetur ridiculus mus etiam vel', 139),
(4, 'maecenas leo odio condimentum id', 110),
(47, 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget', 358),
(29, 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus', 342),
(75, 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio', 244),
(63, 'vestibulum', 289),
(62, 'leo rhoncus sed vestibulum sit amet', 214),
(62, 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', 232),
(99, 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', 177),
(55, 'orci nullam', 200);

--Likes
INSERT INTO Chat.[Like](postId, userId)
VALUES (330, 2),
(314, 10),
(11, 9),
(58, 10),
(245, 6),
(39, 6),
(386, 7),
(13, 9),
(137, 3),
(372, 7),
(26, 1),
(294, 10),
(215, 11),
(288, 8),
(32, 7),
(320, 7),
(399, 4),
(384, 4),
(313, 5),
(335, 10),
(153, 10),
(325, 8),
(179, 8),
(41, 3),
(166, 11),
(12, 6),
(375, 3),
(261, 7),
(366, 2),
(61, 9),
(278, 9),
(71, 1),
(353, 7),
(271, 6),
(277, 1),
(140, 5),
(275, 9),
(304, 1),
(86, 11),
(236, 2),
(213, 3),
(388, 2),
(6, 5),
(375, 2),
(20, 10),
(294, 1),
(90, 3),
(316, 4),
(299, 11),
(33, 2),
(195, 1),
(70, 10),
(328, 10),
(374, 3),
(89, 9),
(273, 10),
(391, 9),
(352, 6),
(56, 10),
(238, 8),
(111, 1),
(130, 8),
(208, 4),
(71, 8),
(10, 10),
(166, 5),
(339, 6),
(379, 6),
(146, 5),
(166, 6),
(88, 8),
(172, 10),
(76, 5),
(65, 9),
(350, 9),
(282, 9),
(59, 7),
(45, 1),
(80, 5),
(51, 4),
(215, 5),
(160, 1),
(101, 8),
(60, 10),
(386, 5),
(216, 2),
(354, 3),
(348, 11),
(135, 2),
(279, 8),
(308, 7),
(280, 3),
(288, 11),
(214, 8),
(104, 2),
(211, 7),
(94, 9),
(312, 2),
(256, 1),
(121, 6),
(398, 9),
(357, 3),
(80, 9),
(351, 5),
(379, 5),
(334, 1),
(65, 10),
(224, 10),
(265, 1),
(309, 11),
(60, 11),
(373, 6),
(143, 9),
(235, 10),
(341, 1),
(274, 1),
(27, 10),
(98, 5),
(325, 1),
(31, 10),
(276, 6),
(16, 1),
(390, 9),
(361, 5),
(5, 6),
(266, 11),
(190, 5),
(328, 4),
(5, 3),
(88, 1),
(399, 8),
(10, 6),
(148, 11),
(365, 10),
(51, 5),
(132, 8),
(67, 11),
(244, 4),
(164, 2),
(30, 3),
(339, 8),
(33, 9),
(3, 1),
(73, 5),
(265, 2),
(317, 5),
(227, 7),
(193, 2),
(218, 9),
(32, 6),
(213, 7),
(64, 11),
(186, 3),
(292, 5),
(203, 10),
(77, 6),
(17, 3),
(301, 11),
(134, 2),
(273, 2),
(65, 6),
(333, 5),
(209, 9),
(238, 3),
(163, 1),
(243, 11),
(347, 9),
(396, 11),
(333, 8),
(236, 1),
(55, 3),
(342, 2),
(21, 3),
(299, 1),
(366, 11),
(290, 11),
(327, 4),
(263, 5),
(209, 8),
(243, 5),
(261, 9),
(86, 9),
(388, 9),
(236, 3),
(376, 1),
(121, 11),
(83, 5),
(336, 4),
(116, 10),
(97, 4),
(133, 8),
(296, 5),
(168, 2),
(379, 7),
(13, 6),
(385, 5),
(144, 7),
(24, 4),
(142, 30),
(213, 68),
(44, 50),
(366, 49),
(124, 82),
(354, 12),
(350, 18),
(261, 18),
(143, 34),
(158, 31),
(240, 46),
(206, 100),
(5, 31),
(139, 56),
(113, 58),
(74, 42),
(209, 22),
(163, 72),
(54, 33),
(194, 63),
(393, 23),
(181, 36),
(306, 54),
(198, 76),
(238, 26),
(316, 82),
(47, 28),
(238, 27),
(370, 21),
(40, 53),
(279, 26),
(208, 75),
(337, 94),
(241, 80),
(174, 26),
(95, 86),
(137, 70),
(332, 68),
(323, 52),
(189, 30),
(345, 17),
(254, 12),
(289, 54),
(336, 58),
(168, 43),
(289, 43),
(223, 34),
(66, 36),
(185, 74),
(338, 54),
(193, 18),
(93, 20),
(109, 30),
(340, 39),
(215, 38),
(90, 25),
(367, 33),
(268, 28),
(201, 52),
(284, 60),
(218, 61),
(102, 13),
(148, 74),
(337, 70),
(383, 15),
(33, 37),
(367, 21),
(308, 93),
(261, 60),
(248, 18),
(182, 35),
(207, 54),
(212, 41),
(253, 37),
(152, 58),
(9, 63),
(228, 62),
(172, 33),
(115, 39),
(343, 73),
(50, 64),
(181, 16),
(268, 30),
(171, 72),
(330, 56),
(365, 51),
(60, 28),
(394, 71),
(350, 91),
(141, 77),
(165, 86),
(161, 39),
(138, 64),
(28, 54),
(346, 69),
(22, 97),
(348, 25),
(349, 79),
(206, 72),
(74, 71),
(100, 95),
(398, 77),
(272, 16),
(65, 61),
(2, 19),
(291, 80),
(30, 26),
(178, 72),
(150, 76),
(175, 37),
(349, 78),
(132, 99),
(195, 70),
(278, 49),
(44, 35),
(285, 13),
(277, 54),
(217, 80),
(204, 13),
(259, 49),
(104, 18),
(347, 84),
(55, 15),
(102, 50),
(120, 87),
(42, 28),
(14, 14),
(18, 96),
(59, 34),
(50, 48),
(220, 86),
(263, 77),
(385, 78),
(193, 42),
(2, 60),
(125, 61),
(77, 13),
(151, 63),
(91, 41),
(360, 63),
(355, 18),
(166, 52),
(384, 51),
(120, 27),
(396, 39),
(209, 31),
(325, 75),
(266, 17),
(345, 47),
(261, 12),
(336, 94),
(107, 94),
(359, 96),
(250, 50),
(155, 72),
(215, 67),
(376, 48),
(179, 94),
(21, 52),
(170, 48),
(114, 30),
(193, 64),
(313, 31),
(345, 73),
(6, 90),
(63, 75),
(306, 74),
(282, 45),
(227, 67),
(23, 20),
(203, 65),
(8, 96),
(135, 49),
(342, 80),
(99, 66),
(252, 26),
(152, 77),
(307, 63),
(300, 85),
(119, 39),
(213, 59),
(44, 31),
(239, 97),
(1, 90),
(379, 12),
(161, 22),
(22, 94),
(244, 28),
(57, 76),
(12, 63),
(344, 55),
(268, 41),
(63, 16),
(195, 22),
(52, 81),
(37, 91),
(308, 90),
(392, 33),
(252, 80),
(397, 55);

--Followers
	--Followers
INSERT INTO Chat.Follower(followedUserId, followerUserId)
VALUES(3, 59),
(10, 88),
(8, 25),
(1, 69),
(8, 39),
(4, 65),
(9, 100),
(2, 50),
(4, 79),
(2, 62),
(6, 15),
(9, 12),
(9, 93),
(8, 84),
(1, 15),
(4, 39),
(1, 87),
(6, 70),
(4, 52),
(2, 100),
(11, 25),
(7, 96),
(4, 69),
(3, 85),
(9, 42),
(8, 77),
(9, 66),
(10, 78),
(4, 31),
(4, 85),
(11, 15),
(6, 69),
(1, 33),
(5, 83),
(7, 97),
(7, 34),
(6, 98),
(4, 73),
(4, 78),
(2, 43),
(8, 13),
(5, 35),
(8, 91),
(8, 78),
(8, 76),
(9, 28),
(7, 72),
(5, 89),
(7, 55),
(11, 49),
(1, 80),
(9, 21),
(4, 80),
(6, 35),
(8, 59),
(6, 34),
(3, 29),
(8, 65),
(1, 31),
(6, 81),
(4, 62),
(4, 81),
(9, 43),
(8, 21),
(2, 17),
(5, 26),
(8, 48),
(11, 20),
(3, 12),
(6, 71),
(10, 46),
(11, 53),
(9, 40),
(6, 91),
(5, 45),
(2, 57),
(2, 83),
(4, 13),
(11, 90),
(1, 75),
(7, 84),
(9, 80),
(11, 70),
(5, 72),
(9, 57),
(6, 23),
(3, 23),
(1, 81),
(2, 16),
(9, 22),
(7, 16),
(4, 48),
(5, 37),
(6, 93),
(6, 86),
(11, 12),
(8, 19),
(7, 39),
(9, 19),
(2, 76),
(7, 41),
(4, 37),
(5, 14),
(9, 60),
(7, 92),
(7, 59),
(3, 16),
(11, 61),
(6, 90),
(8, 24),
(2, 54),
(7, 26),
(5, 65),
(9, 70),
(7, 56),
(2, 59),
(5, 79),
(5, 90),
(8, 51),
(10, 86),
(5, 77),
(2, 40),
(10, 45),
(2, 44),
(8, 95),
(7, 43),
(8, 69),
(10, 75),
(4, 34),
(2, 26),
(2, 19),
(1, 39),
(3, 76),
(5, 13),
(7, 86),
(8, 81),
(10, 64),
(2, 18),
(3, 74),
(9, 34),
(5, 86),
(8, 86),
(2, 15),
(6, 64),
(6, 75),
(2, 53),
(10, 33),
(11, 42),
(6, 58),
(5, 62),
(4, 44),
(7, 91),
(2, 95),
(1, 44),
(2, 46),
(8, 16),
(9, 20),
(5, 80),
(11, 76),
(7, 47),
(8, 62),
(10, 36),
(3, 25),
(1, 46),
(3, 38),
(3, 62),
(7, 53),
(2, 77),
(8, 73),
(3, 54),
(6, 55),
(7, 87),
(5, 18),
(3, 90),
(2, 84),
(8, 22),
(3, 63),
(11, 28),
(7, 60),
(9, 79),
(6, 33),
(6, 47),
(9, 46),
(6, 67),
(5, 56),
(4, 92),
(2, 82),
(22, 3),
(33, 11),
(80, 4),
(28, 7),
(63, 3),
(49, 6),
(1, 2),
(69, 7),
(22, 4),
(83, 4),
(62, 5),
(93, 6),
(61, 5),
(60, 2),
(30, 10),
(39, 10),
(97, 5),
(69, 11),
(62, 4),
(7, 11),
(44, 4),
(84, 2),
(85, 5),
(21, 1),
(38, 3),
(5, 10),
(58, 2),
(26, 4),
(11, 7),
(54, 10),
(64, 1),
(51, 10),
(13, 7),
(70, 2),
(7, 1),
(72, 10),
(33, 7),
(90, 8),
(20, 11),
(96, 11),
(99, 11),
(84, 6),
(48, 11),
(55, 11),
(40, 4),
(62, 6),
(53, 8);
